

version: '2'

networks:
  test:



services:
  couchdbOrg1Peer0:
    container_name: couchdbOrg1Peer0
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=fotorg1peer0user
      - COUCHDB_PASSWORD=fotproddbadminpw
    networks:
      - test
    ports:
      - 5984:5984
    volumes:
      - ../backup/org1-peer0-couchdbData:/opt/couchdb/data

  peer0.org1.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbOrg1Peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=fotorg1peer0user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=fotproddbadminpw
    depends_on:
      - couchdbOrg1Peer0

  couchdbOrg1Peer1:
    container_name: couchdbOrg1Peer1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=fotorg1peer1user
      - COUCHDB_PASSWORD=fotproddbadminpw
    networks:
      - test
    ports:
      - 6984:5984
    volumes:
      - ../backup/org1-peer1-couchdbData:/opt/couchdb/data

  peer1.org1.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbOrg1Peer1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=fotorg1peer1user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=fotproddbadminpw
    depends_on:
      - couchdbOrg1Peer1

  peer2.org1.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbOrg1Peer2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=fotorg1peer2user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=fotproddbadminpw
    depends_on:
      - couchdbOrg1Peer2
